---
postgis:
  prefix_major_version:
  major_version: 2
  minor_version: 5
  patch_version: .4+pivotal.8.build.1
  gpdb_version: 6
  os_version: rhel9
  database_name: postgis_testdb
  schema_name: postgis_test_scheme
  mdw_hostname: rh9-node01

# postgis-2.5.4+pivotal.8.build.1-gp6-rhel9-x86_64.gppkg
# postgis-2.5.4+pivotal.8.build.1-gp6-rhel7-x86_64.gppkg
# postgis-3.3.2+pivotal.1.build.1-gp7-rhel8-x86_64.gppkg
# postgis-2.5.4+pivotal.7.build.1-gp6-rhel8-x86_64.gppkg
# postgis-2.5.4+pivotal.6.build.1-gp6-rhel8-x86_64.gppkg
# postgis-2.5.4+pivotal.3.build.7-gp6-rhel7-x86_64.gppkg
# postgis-2.1.5+pivotal.2-8-gp6-rhel7-x86_64.gppkg
# postgis-2.1.5+pivotal.2-8-gp6-rhel7-x86_64.gppkg
# postgis-2.1.5+pivotal.2-gp5-rhel7-x86_64.gppkgg
# postgis-ossv2.0.3_pv2.0.2_gpdb4.3orca-rhel5-x86_64.gppkg
# postgis-2.1.5+pivotal.2-2-gp6-rhel7-x86_64.gppkg
# postgis-2.5.4+pivotal.2.build.3-gp6-rhel7-x86_64.gppkg
# postgis-2.5.4+pivotal.4.build.3-gp6-rhel7-x86_64.gppkg

